rosbag_path: "/home/asensioh/Escritorio/rosbags/optitrack/occlusions/rodri_occlusion_opti_1_filtered.bag"
rosbag_start_time: 1764591188.125251
delay_optitrack_sec: 3.5 # Se asume (+) por defecto
optitrack_csv_path: "/media/asensioh/PortableSSD/Experimento nov 2025 optitrack/pc_imech/rodri_occlusion_1_reconstructed.csv"
reconstruir_elbow_1_opti: true

# Parámetros antropométricos
d: 0.08
l1: 0.32
l2: 0.27

checks:
  optitrack_csv_processed: true
  optitrack_csv_reconstructed: true
  rosbag_filtered: true

