rosbag_path: ""
rosbag_start_time: 
delay_optitrack_sec: # Delay es un offset temporal. Ejemplo: Para delay -4, si empezaba en 0, ahora empieza en -4.0. 
optitrack_csv_path: ""

d: 
l1: 
l2: 

checks:
  optitrack_csv_processed: false
  rosbag_filtered: false

experiment_notes: ""
